name: First Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print my name
        run: echo "My name is Kiran"

      - name: Show date
        run: date

      - name: List files
        run: ls -la